default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
big-publish: styles/enable-big-publish.scss
wide-column: styles/enable-wide-column.scss
big-and-wide: styles/enable-big-and-wide.scss